### PR TITLE
adding scaffolding section to js

### PR DESCRIPTION
**Pull request by TheOneTheOnlyDavidBrown**
Scaffolding tools are an important part of modern front end workflow and should be included

### CODE REVIEW

**Comment by codylindley** [comment]
Thanks for the request here. I need to think about it and where I might add this. I've personally never used a scaffolding tool and I am not even aware of anyone who does use one that is generic. Let me think more about it.

**Comment by 1Marc** [comment]
I've never used Yeoman either. But shouldn't it just be under "build tools"? I guess it does push out boiler plate code for you. So does the Ember CLI. I still would consider them build tools though.

**Comment by codylindley** [comment]
@1Marc - Yes, forsure yeoman is a build'ish tool. I wrestling with this as well because I've never seen the need for it when using something like Ember or Meteor as most app tools have their own CLI.

**Comment by codylindley** [comment]
I'm curious @TheOneTheOnlyDavidBrown , besides yeoman what other scaffolding tools would fall into a category with yeoman?

**Comment by TheOneTheOnlyDavidBrown** [comment]
Slush is another scaffolding tool. I would consider both to be more of a workflow tool than a build tool as they eliminate a lot repetitive tasks and handle the organization in a consistent manner.

If you want to take a look at a project that uses Yeoman extensively, spin up an Angular project with generator-ng-poly.
https://github.com/dustinspecker/generator-ng-poly

**Comment by codylindley** [comment]
I added a section. 

http://www.frontendhandbook.com/tools/scaffolding.html

**Pull request closed without merging**
